# --- PLUGINS ---
set -g @plugin 'psmux-plugins/ppm'
set -g @plugin 'psmux-plugins/psmux-sensible'
set -g @plugin 'psmux-plugins/psmux-pain-control'

# Restore sessions on reboot
set -g @plugin 'psmux-plugins/psmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'


# --- CORE SETTINGS ---
set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

set -g default-terminal "tmux-256color"

set -g mouse off
set -g base-index 1
set -g pane-base-index 1
set -g history-limit 5000
set -g allow-rename off
set -sg escape-time 1
set-window-option -g mode-keys vi

# --- COLORS & STYLE ---
set -g status-position bottom
set -g status-justify absolute-centre
set -g status-style "bg=#000000"

# LEFT: Session Name (changes color when prefix is active)
set -g status-left-length 50
set -g status-left "#{?client_prefix,#[bg=#95E6CB]#[fg=#0B0E14] bold #S ,#[bg=default]#[fg=#41474b] #S }#[bg=default] #{client_key_table}"

# RIGHT: Time
set -g status-right-length 50
set -g status-right "#[fg=#41474b,bg=default] %H:%M "

# --- WINDOW LIST ---
set -g window-status-separator " • "

# Inactive Window - Darker Grey
set -g window-status-format " #W "
set -g window-status-style "bg=default,fg=#41474b"

# Active Window - White Text with Zoom Flag in #4488a3
# I used a conditional check so the icon only shows when zoomed
set -g window-status-current-format "#[fg=#ffffff,bg=default,bold] #W #[fg=#4488a3,none]󰊓"
set -g window-status-current-style "bg=default,fg=#ffffff,bold"

# --- KEY BINDINGS ---
# Move Between Panes
unbind z
bind-key z switch-client -T MOVE

bind-key -T MOVE h select-pane -L \; switch-client -T MOVE
bind-key -T MOVE l select-pane -R \; switch-client -T MOVE
bind-key -T MOVE k select-pane -U \; switch-client -T MOVE
bind-key -T MOVE j select-pane -D \; switch-client -T MOVE

# Split Panes (Side-by-side and Top-bottom)
unbind-key s
bind-key s switch-client -T SPLIT
bind-key -T SPLIT v split-window -h -c "#{pane_current_path}"
bind-key -T SPLIT h split-window -v -c "#{pane_current_path}"

# Window Navigation
bind-key n next-window
bind-key p previous-window

# Standard Utility
bind-key c new-window -c "#{pane_current_path}"

# Resize panes more easily
bind-key < resize-pane -L 10
bind-key > resize-pane -R 10
bind-key - resize-pane -D 10
bind-key + resize-pane -U 10

# --- EXTRA OPTIONS ---
# Predictions
set -g allow-predictions on
set -g prediction-dimming on

# Cursor settings
set -g cursor-style block
set -g cursor-blink on

# Initialize PPM (keep at the very bottom)
run '~/.psmux/plugins/ppm/ppm.ps1'
